Jenkings configuration
bitflow-stream/bitflow4j pull request #38
Opened 2019-05-07 15:07 UTC by antongulenko

Added Jenkinsfile for tests, coverage and docker container building. Fixed pom for tests.

2019-05-07 15:08 UTC, antongulenko commented
When merging this PR, please select "squash commit" to remove the useless intermediate commits.

2019-05-07 15:51 UTC, antongulenko commented on Jenkinsfile
> +            withSonarQubeEnv('CIT SonarQube') {
Pls move this stage to after tests

2019-05-07 16:17 UTC, srnbckr commented
I'm still testing some stuff. Please do not merge yet.

2019-05-07 16:41 UTC, srnbckr commented on Jenkinsfile
> +            withSonarQubeEnv('CIT SonarQube') {
done

2019-05-07 16:41 UTC, srnbckr commented
I'm done. Ready to merge from my side.

2019-05-08 13:45 UTC, flohannes requested changes

2019-05-08 13:45 UTC, flohannes commented on Jenkinsfile
> +            //when {
remove those outcomment lines pleeeease :)

2019-05-08 15:03 UTC, flohannes approved these changes

2019-05-08 15:04 UTC, merged