Feature aggregation batch and samplewise
bitflow-stream/bitflow4j pull request #65
Opened 2019-07-05 09:49 UTC by kevinstyp

2019-07-05 10:31 UTC, kevinstyp commented
Please do not merge yet.
This contains a bug or weird behaviour. Users can not specify "input" yet as only one sample gets emitted, where the user would expect the whole batch to be emitted.

2019-07-18 15:37 UTC, kevinstyp commented
Can be merged now 👍

2019-07-18 15:46 UTC, antongulenko requested changes
Looks good! Please refactor the two toString() methods, since they contain duplicated code. Could be put into the utils class, as a static formatString() method, that receives the list of getters and suffixes, and a non-static toString() method that uses the static one.

2019-07-19 08:59 UTC, antongulenko approved these changes

2019-07-19 09:00 UTC, merged